alter table public.crew_profiles
  add column if not exists role text not null default 'crew'
  check (role in ('crew', 'crew_trainer', 'manager', 'first_assistant', 'store_manager'));

update public.crew_profiles
set role = case lower(first_name)
  when 'dylan' then 'store_manager'
  when 'manu' then 'first_assistant'
  when 'luca' then 'manager'
  when 'maxime' then 'manager'
  else role
end;

alter table public.crew_profiles alter column ranked_points set default 0;
update public.crew_profiles set ranked_points = 0 where ranked_matches = 0;

create table if not exists public.task_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(trim(name)) between 2 and 60),
  created_by uuid references public.crew_profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.crew_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(trim(title)) between 3 and 180),
  category_id uuid not null references public.task_categories(id) on delete restrict,
  created_by uuid not null references public.crew_profiles(id) on delete restrict,
  due_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'todo', 'doing', 'done')),
  taken_by uuid references public.crew_profiles(id) on delete set null,
  approved_by uuid references public.crew_profiles(id) on delete set null,
  approved_at timestamptz,
  completed_by uuid references public.crew_profiles(id) on delete set null,
  completed_at timestamptz,
  completion_note text check (completion_note is null or char_length(completion_note) <= 800),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.task_events (
  id bigint generated by default as identity primary key,
  task_id uuid references public.crew_tasks(id) on delete cascade,
  actor_id uuid not null references public.crew_profiles(id) on delete restrict,
  action text not null check (action in ('created', 'approved', 'taken', 'completed', 'role_changed', 'category_created')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.task_categories enable row level security;
alter table public.crew_tasks enable row level security;
alter table public.task_events enable row level security;

insert into public.task_categories (name, created_by)
select category.name, manager.id
from (values ('Nettoyage'), ('Surveillance'), ('Maintenance'), ('Organisation')) as category(name)
cross join (select id from public.crew_profiles where role = 'store_manager' limit 1) as manager
on conflict (name) do nothing;

create index if not exists crew_tasks_status_due_at_idx on public.crew_tasks(status, due_at);
create index if not exists task_events_task_created_at_idx on public.task_events(task_id, created_at desc);
