create table if not exists public.identity_login_attempts (
  id bigint generated by default as identity primary key,
  identity_normalized text not null,
  attempted_at timestamptz not null default now()
);

alter table public.identity_login_attempts enable row level security;
create index if not exists identity_login_attempts_identity_time_idx on public.identity_login_attempts(identity_normalized, attempted_at desc);
